# URL temporal - cambiar cuando tengas dominio
base_url = "https://example.com"
title = "Entroponomist"
description = "Blog personal de un estudiante tech savvy de economía"
theme = "tabi"
default_language = "es"

# Configuraciones que elegiste en zola init
compile_sass = true
build_search_index = true

# Taxonomías
[[taxonomies]]
name = "tags"
feed = true
paginate_by = 5
paginate_path = "page"

# Configuración de markdown
[markdown]
highlight_code = true
highlight_theme = "css"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

# Configuración del tema tabi
[extra]
# Apariencia
theme_switcher = false
default_theme = "dark"
skin = "lavender"  # Puedes cambiar: teal, lavender, red, mint, sakura, blue, etc.

# Tu información (actualiza con tus datos reales)
email = "tu@email.com"  # Cambiar por tu email real
author = "Tu Nombre"    # Cambiar por tu nombre real
copyright = "© 2025 Tu Nombre. Todos los derechos reservados."

# Configuración de seguridad (optimizada para Cloudflare)
enable_csp = true
allowed_domains = [
    { directive = "font-src", domains = ["'self'", "data:"] },
    { directive = "img-src", domains = ["'self'", "https://*", "data:"] },
    { directive = "script-src", domains = ["'self'"] },
    { directive = "style-src", domains = ["'self'"] },
    { directive = "connect-src", domains = ["'self'"] },
]

# Menú de navegación
[[extra.menu]]
name = "Inicio"
url = "/"

[[extra.menu]]
name = "Blog"
url = "/blog/"

[[extra.menu]]
name = "Proyectos"
url = "/projects/"

[[extra.menu]]
name = "Archivo"
url = "/archive/"

[[extra.menu]]
name = "Sobre-mi"
url = "/about/"

# Redes sociales (actualiza con tus perfiles reales)
[[extra.socials]]
name = "github"
icon = "github"
url = "https://github.com/just-gam"

[[extra.socials]]
name = "twitter"
icon = "twitter"
url = "https://twitter.com/tu-usuario"

[[extra.socials]]
name = "linkedin"
icon = "linkedin"
url = "https://linkedin.com/in/tu-perfil"

# Configuración de comentarios (la configuraremos después)
[extra.giscus]
enabled_for_all_posts = false
automatic_loading = true
# repo = "tu-usuario/tu-blog"  # Descomentar cuando tengas el repo
# Los demás campos los configuraremos cuando tengas dominio
